Create SliderBanner component
DJ-Java-Team/youmiteru-frontend pull request #17
Opened 2024-01-15 13:41 UTC by Taps73r

Create SliderBanner component:
1) SliderBanner with react-slick and scss styles
2) Response for mobile and other devices.
3) SampleArrow component for slider.
Update package.json:
Added new dependencies:
"@types/react-slick", "react-slick", "slick-carousel" for slider working.

2024-01-15 15:45 UTC, Kumala3 commented on frontend/src/components/SliderButtons/SampleNextArrow.tsx
### Great naming for the arrow components!
#### Change "SampleNextArrow" function name and the component and do the same with "PrevArrow" and don't forget about styles component name too!

2024-01-15 17:20 UTC, Taps73r commented
Can you review all the changes in the new commit? All the modifications made are described there.

2024-01-16 22:36 UTC, Kumala3 commented on frontend/package.json
### Update dependencies up to date with the develop branch please!

2024-01-16 22:38 UTC, Kumala3 commented on frontend/src/components/SliderButtons/NextArrow.tsx
Make empty line between interface and imports as you do everywhere other.

2024-01-16 22:40 UTC, Kumala3 commented on frontend/src/components/SliderButtons/SliderButton.scss
Make empty lines between styles for more readable, please.

2024-01-16 22:42 UTC, Kumala3 commented on frontend/src/components/SliderBanner/SliderBanner.tsx
Update your SliderBanner up to date with develop branch. I mean change string param to Banner from types and make only one empty line between imports and interface not two.

2024-01-16 23:49 UTC, Taps73r commented
Check new changes in PR.
Merge develop branch with feature/component/sliderbanner branch.
Resolve conflict in package.json.
Change interface in SliderBanner.
Change name for props in SliderBanner.

2024-01-17 06:43 UTC, Kumala3 requested changes
Delete unnecessary images from the project.
Don't forget to add a newline at the end of code, everywhere where it isn't.

2024-01-17 07:05 UTC, Taps73r commented
Delete test pictures from the project.
Add newline at the end

2024-01-18 23:01 UTC, Taps73r commented
**Ch### anges in the SliderBanner.scss file:**

- Made the height and width of the slide dependent on the device screen width.
- Reduced the spacing between slides.
- Increased the value of transform: scale.
### 
**Changes in the SliderBanner.tsx file:**

- Modified responsive settings by adding onFocus for mobile phones and tablets, removed unnecessary settings.
- Adjusted the interface according to the new responsive settings.

2024-01-19 21:33 UTC, Taps73r commented
### .scss flies change:
add background for buttons,
delete border for buttons and change button size,
in all .scss files add 4 space for better reading.

### NextArrow.tsx PrevArrow.tsx change:
change div to button and fix interface

2024-01-20 09:38 UTC, Kumala3 approved these changes
### Great job, keep it up! PR include everything what was described in #17.
PR can be merged with the develop branch.

2024-01-20 09:38 UTC, merged